backend:
  name: git-gateway
  repo: elodiefoucher/pslm-website # Path to your GitHub repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "static/img/" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "secteur-competition" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Secteur Competition" # Used in the UI, ie.: "New Post"
    folder: "content/gym-competition-adherents" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Début Compet", name: "date", widget:"date"}
      - {label: "Fin Compet", name: "end", widget:"date"}
      - {label: "Lieu", name: "lieu", widget: "string"}
      - {label: "Passage", name: "passage", widget:"file"}
      - {label: "Convocation", name: "convocation", widget:"file"}
      - {label: "Resulats", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget:"string"}
      - {label: "Résultats", name: "resultats", required: false, widget: list, fields: [
          {label: "Catégorie", name: "categorie", widget: list, fields: [
            {label: "Athlètes", name: "athlete", widget: "list", fields: [
              {label: "Nom", name: "nom", widget: "string"},
              {label: "Place", name: "place", widget: "string"},
              {label: "Points", name: "points", widget: "string"}
            ]}
            ]}
          ]}
  - name: "ateliers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Ateliers" # Used in the UI, ie.: "New Post"
    folder: "content/ateliers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Categories", name: categories, widget: list}
      - {label: "Tags", name: tags, widget: list, default: ['term_1', 'term_2']}
      - {label: "Tarif", name: "tarif", widget: "string"}
      - {label: "Image Banner", name: "banner", widget:"image"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Parent", name: "parent", widget: "string"}
      - {label: "Recurrent", name: "recurring", widget: "string"}
      - {label: "Recurrence", name: "recurrence", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: porteurs
        label: Animateurs
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
      - name: documentation
        label: Documentation
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
      - name: ressources
        label: Ressources
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}

  - name: "evenements" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Evenements" # Used in the UI, ie.: "New Post"
    folder: "content/agenda" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: Categories, name: categories, widget: list}
      - {label: Tags, name: tags, widget: list, default: ['term_1', 'term_2']}
      - {label: Lieu, name: lieu, widget: "string"}
      - {label: "Quand", name: "start", widget: "datetime"}
      - {label: "Fin", name: "end", widget: "datetime"}
      - {label: "Tarif", name: "tarif", widget: "string"}
      - {label: "Image Banner", name: "banner", widget:"image"}
      - {label: "Thumbnail", name: "thumbnail", widget:"image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Parent", name: "parent", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - name: porteurs
        label: Animateurs
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
      - name: documentation
        label: Documentation
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
      - name: ressources
        label: Ressources
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Lien, name: link, widget: string}
