backend:
  name: git-gateway
  repo: elodiefoucher/pslm-website # Path to your GitHub repository
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "static/img/" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "actualite" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Actualité" # Used in the UI, ie.: "New Post"
    folder: "content/actualite" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image d'accueil (Format paysage)", name: "galerieaccueil", widget: "image"}
      - {label: "Galerie", name: galerie, widget: "list", fields: [
          {label: "Photo", name: "photo", widget: "image"}]}
      - {label: "Accueil (Début tronqué de l'article, environ les 2 premières lignes)", name: "accueil", widget: "string"}
      - {label: "Article", name: "body", widget: "markdown"}

  - name: "gym-competition" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Gym Compétition Adhérents" # Used in the UI, ie.: "New Post"
    folder: "content/gym-competition-adherents" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Début Compet", name: "date", widget: "date"}
      - {label: "Fin Compet", name: "end", widget: "date"}
      - {label: "Lieu", name: "lieu", widget: "string"}
      - {label: "Ordre de Passage", name: "passage", required: false, widget: "file"}
      - {label: "Convocation", name: "convocation", required: false, widget: "file"}
      - {label: "Résultats", name: "resultats", required: false, widget: list, fields: [
          {label: "Catégorie", name: "categorie", widget: "string"},
          {label: "Athlètes", name: "athlete", widget: "list", fields: [
              {label: "Nom", name: "nom", widget: "string"},
              {label: "Place", name: "place", widget: "string"},
              {label: "Points", name: "points", widget: "string"}]}]}

  - name: "gym-fitness-adherents" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Gym Fitness Adhérents" # Used in the UI, ie.: "New Post"
    folder: "content/gym-fitness-adherents" # The path to the folder where the documents are stored
    fields:
      - {label: "Infos", name: "body", widget: "markdown"}

  - name: "danse-adherents" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Danse Adhérents" # Used in the UI, ie.: "New Post"
    folder: "content/danse-adherents" # The path to the folder where the documents are stored
    fields:
      - {label: "Infos", name: "body", widget: "markdown"}

  - name: "portraits" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Portraits" # Used in the UI, ie.: "New Post"
    folder: "content/portraits" # The path to the folder where the documents are stored
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Mois Année", name: "jour", widget: "string"}
      - {label: "Image d'accueil (photo ronde)", name: "galerieaccueil", widget: "image"}
      - {label: "Galerie", name: galerie, widget: list, fields: [
          {label: "Photo", name: "photo", widget: "image"}]}
      - {label: "Article", name: "body", widget: "markdown"}

  - name: "inscription" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Inscription" # Used in the UI, ie.: "New Post"
    folder: "content/inscription" # The path to the folder where the documents are stored
    fields:
      - {label: "Documents d'inscription", name: "documents", widget: list, fields: [
              {label: "Section", name: "nom", widget: "string"},
              {label: "Doc", name: "lien", widget: "file"}]}
